// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: uCNC-GFX

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_startup
void ui_startup_screen_init(void);
lv_obj_t * ui_startup;
lv_obj_t * ui_startup_label_versioninfo;
lv_obj_t * ui_startup_image_image1;


// SCREEN: ui_idle
void ui_idle_screen_init(void);
lv_obj_t * ui_idle;
lv_obj_t * ui_idle_container_header2;
lv_obj_t * ui_idle_button_btnhome;
lv_obj_t * ui_idle_label_btnhomelabel;
lv_obj_t * ui_idle_container_statusinfo;
lv_obj_t * ui_idle_label_statuslabel;
lv_obj_t * ui_idle_label_statusvalue;
lv_obj_t * ui_idle_button_btnholdres;
lv_obj_t * ui_idle_label_btnholdreslabel;
lv_obj_t * ui_idle_container_body2;
lv_obj_t * ui_idle_container_container1;
lv_obj_t * ui_idle_container_modalmodesinfo;
lv_obj_t * ui_idle_label_modalmodeslabel;
lv_obj_t * ui_idle_label_modalmodesvalue;
lv_obj_t * ui_idle_container_container3;
lv_obj_t * ui_idle_label_unitsvalue;
lv_obj_t * ui_idle_container_feedinfo;
lv_obj_t * ui_idle_label_feedlabel;
lv_obj_t * ui_idle_label_feedvalue;
lv_obj_t * ui_idle_container_toolnumberinfo;
lv_obj_t * ui_idle_label_toolnumberlabel;
lv_obj_t * ui_idle_label_toolnumbervalue;
lv_obj_t * ui_idle_container_toolspeedinfo;
lv_obj_t * ui_idle_label_toolspeedlabel;
lv_obj_t * ui_idle_label_toolspeedvalue;
lv_obj_t * ui_idle_container_switchinfo;
lv_obj_t * ui_idle_label_switchlabel;
lv_obj_t * ui_idle_label_switchvalue;
lv_obj_t * ui_idle_axisinfo_axisinfox;
lv_obj_t * ui_idle_axisinfo_axisinfoy;
lv_obj_t * ui_idle_axisinfo_axisinfoz;
lv_obj_t * ui_idle_axisinfo_axisinfoa;
lv_obj_t * ui_idle_axisinfo_axisinfob;
lv_obj_t * ui_idle_axisinfo_axisinfoc;
lv_obj_t * ui_idle_container_footer2;
void ui_event_idle_button_btnprev2(lv_event_t * e);
lv_obj_t * ui_idle_button_btnprev2;
lv_obj_t * ui_idle_label_btnprevlabel2;
void ui_event_idle_button_btnnext2(lv_event_t * e);
lv_obj_t * ui_idle_button_btnnext2;
lv_obj_t * ui_idle_label_btnnextlabel2;
void ui_event_idle_button_btnenter2(lv_event_t * e);
lv_obj_t * ui_idle_button_btnenter2;
lv_obj_t * ui_idle_label_btnenterlabel2;


// SCREEN: ui_navigate
void ui_navigate_screen_init(void);
lv_obj_t * ui_navigate;
lv_obj_t * ui_navigate_panel_headernav;
lv_obj_t * ui_navigate_label_headerlabel;
void ui_event_navigate_button_btnclose(lv_event_t * e);
lv_obj_t * ui_navigate_button_btnclose;
lv_obj_t * ui_navigate_label_btncloselabel;
lv_obj_t * ui_navigate_container_body;
lv_obj_t * ui_navigate_container_menuitem0;
lv_obj_t * ui_navigate_label_menuitemlabel;
lv_obj_t * ui_navigate_label_menuitemvalue;
lv_obj_t * ui_navigate_container_menuitem1;
lv_obj_t * ui_navigate_label_menuitemlabel1;
lv_obj_t * ui_navigate_label_menuitemvalue1;
lv_obj_t * ui_navigate_container_menuitem2;
lv_obj_t * ui_navigate_label_menuitemlabel2;
lv_obj_t * ui_navigate_label_menuitemvalue2;
lv_obj_t * ui_navigate_container_menuitem3;
lv_obj_t * ui_navigate_label_menuitemlabel3;
lv_obj_t * ui_navigate_label_menuitemvalue3;
lv_obj_t * ui_navigate_container_menuitem4;
lv_obj_t * ui_navigate_label_menuitemlabel4;
lv_obj_t * ui_navigate_label_menuitemvalue4;
lv_obj_t * ui_navigate_container_menuitem5;
lv_obj_t * ui_navigate_label_menuitemlabel5;
lv_obj_t * ui_navigate_label_menuitemvalue5;
lv_obj_t * ui_navigate_container_menuitem6;
lv_obj_t * ui_navigate_label_menuitemlabel6;
lv_obj_t * ui_navigate_label_menuitemvalue6;
lv_obj_t * ui_navigate_container_menuitem7;
lv_obj_t * ui_navigate_label_menuitemlabel7;
lv_obj_t * ui_navigate_label_menuitemvalue7;
lv_obj_t * ui_navigate_container_menuitem8;
lv_obj_t * ui_navigate_label_menuitemlabel8;
lv_obj_t * ui_navigate_label_menuitemvalue8;
lv_obj_t * ui_navigate_container_footer;
lv_obj_t * ui_navigate_panel_footernav;
void ui_event_navigate_button_btnprev(lv_event_t * e);
lv_obj_t * ui_navigate_button_btnprev;
lv_obj_t * ui_navigate_label_btnprevlabel;
void ui_event_navigate_button_btnnext(lv_event_t * e);
lv_obj_t * ui_navigate_button_btnnext;
lv_obj_t * ui_navigate_label_btnnextlabel;
void ui_event_navigate_button_btnenter(lv_event_t * e);
lv_obj_t * ui_navigate_button_btnenter;
lv_obj_t * ui_navigate_label_btnenterlabel;


// SCREEN: ui_edit
void ui_edit_screen_init(void);
lv_obj_t * ui_edit;
lv_obj_t * ui_edit_panel_headeredit;
lv_obj_t * ui_edit_label_headerlabel2;
void ui_event_edit_button_btnclose2(lv_event_t * e);
lv_obj_t * ui_edit_button_btnclose2;
lv_obj_t * ui_edit_label_btncloselabel2;
lv_obj_t * ui_edit_container_bodyedit;
lv_obj_t * ui_edit_textarea_vareditinput;
lv_obj_t * ui_edit_container_footeredit;
lv_obj_t * ui_edit_keyboard_keyboardedit;


// SCREEN: ui_jog
void ui_jog_screen_init(void);
lv_obj_t * ui_jog;
lv_obj_t * ui_jog_panel_headernav1;
lv_obj_t * ui_jog_label_headerlabel1;
void ui_event_jog_button_btnclose1(lv_event_t * e);
lv_obj_t * ui_jog_button_btnclose1;
lv_obj_t * ui_jog_label_btncloselabel1;
lv_obj_t * ui_jog_container_body1;
lv_obj_t * ui_jog_panel_panel1;
lv_obj_t * ui_jog_container_container2;
lv_obj_t * ui_jog_label_label4;
lv_obj_t * ui_jog_roller_jogdist;
lv_obj_t * ui_jog_container_container4;
lv_obj_t * ui_jog_label_label5;
lv_obj_t * ui_jog_roller_jogfeed;
lv_obj_t * ui_jog_container_container5;
lv_obj_t * ui_jog_label_label6;
lv_obj_t * ui_jog_roller_jogaxis;
lv_obj_t * ui_jog_container_container6;
lv_obj_t * ui_jog_button_btnjogplus;
lv_obj_t * ui_jog_label_label2;
lv_obj_t * ui_jog_button_btnjogcancel;
lv_obj_t * ui_jog_label_label3;
lv_obj_t * ui_jog_button_btnjogminus;
lv_obj_t * ui_jog_label_label7;
lv_obj_t * ui_startevents____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_idle_button_btnprev2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_prev_cb(e);
    }
}
void ui_event_idle_button_btnnext2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_next_cb(e);
    }
}
void ui_event_idle_button_btnenter2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_enter_cb(e);
    }
}
void ui_event_navigate_button_btnclose(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_close_cb(e);
    }
}
void ui_event_navigate_button_btnprev(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_prev_cb(e);
    }
}
void ui_event_navigate_button_btnnext(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_next_cb(e);
    }
}
void ui_event_navigate_button_btnenter(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_enter_cb(e);
    }
}
void ui_event_edit_button_btnclose2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_close_cb(e);
    }
}
void ui_event_jog_button_btnclose1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        touch_btn_close_cb(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_startup_screen_init();
    ui_idle_screen_init();
    ui_navigate_screen_init();
    ui_edit_screen_init();
    ui_jog_screen_init();
    ui_startevents____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_startup);
}
