// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: uCNC-GFX

#ifndef _UCNC_GFX_UI_H
#define _UCNC_GFX_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "../../lvgl/lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_startup
void ui_startup_screen_init(void);
extern lv_obj_t * ui_startup;
extern lv_obj_t * ui_startup_label_versioninfo;
extern lv_obj_t * ui_startup_image_logo;
// SCREEN: ui_idle
void ui_idle_screen_init(void);
extern lv_obj_t * ui_idle;
extern lv_obj_t * ui_idle_container_header2;
extern lv_obj_t * ui_idle_button_btnhome;
extern lv_obj_t * ui_idle_label_btnhomelabel;
extern lv_obj_t * ui_idle_container_statusinfo;
extern lv_obj_t * ui_idle_label_statuslabel;
extern lv_obj_t * ui_idle_label_statusvalue;
extern lv_obj_t * ui_idle_button_btnholdres;
extern lv_obj_t * ui_idle_label_btnholdreslabel;
extern lv_obj_t * ui_idle_container_body2;
extern lv_obj_t * ui_idle_container_container1;
extern lv_obj_t * ui_idle_container_modalmodesinfo;
extern lv_obj_t * ui_idle_label_modalmodeslabel;
extern lv_obj_t * ui_idle_label_modalmodesvalue;
extern lv_obj_t * ui_idle_container_container3;
extern lv_obj_t * ui_idle_label_unitsvalue;
extern lv_obj_t * ui_idle_container_feedinfo;
extern lv_obj_t * ui_idle_label_feedlabel;
extern lv_obj_t * ui_idle_label_feedvalue;
extern lv_obj_t * ui_idle_container_toolnumberinfo;
extern lv_obj_t * ui_idle_label_toolnumberlabel;
extern lv_obj_t * ui_idle_label_toolnumbervalue;
extern lv_obj_t * ui_idle_container_toolspeedinfo;
extern lv_obj_t * ui_idle_label_toolspeedlabel;
extern lv_obj_t * ui_idle_label_toolspeedvalue;
extern lv_obj_t * ui_idle_container_switchinfo;
extern lv_obj_t * ui_idle_label_switchlabel;
extern lv_obj_t * ui_idle_label_switchvalue;
extern lv_obj_t * ui_idle_axisinfo_axisinfox;
extern lv_obj_t * ui_idle_axisinfo_axisinfoy;
extern lv_obj_t * ui_idle_axisinfo_axisinfoz;
extern lv_obj_t * ui_idle_axisinfo_axisinfoa;
extern lv_obj_t * ui_idle_axisinfo_axisinfob;
extern lv_obj_t * ui_idle_axisinfo_axisinfoc;
extern lv_obj_t * ui_idle_container_footer2;
void ui_event_idle_button_btnprev2(lv_event_t * e);
extern lv_obj_t * ui_idle_button_btnprev2;
extern lv_obj_t * ui_idle_label_btnprevlabel2;
void ui_event_idle_button_btnnext2(lv_event_t * e);
extern lv_obj_t * ui_idle_button_btnnext2;
extern lv_obj_t * ui_idle_label_btnnextlabel2;
void ui_event_idle_button_btnenter2(lv_event_t * e);
extern lv_obj_t * ui_idle_button_btnenter2;
extern lv_obj_t * ui_idle_label_btnenterlabel2;
// SCREEN: ui_navigate
void ui_navigate_screen_init(void);
extern lv_obj_t * ui_navigate;
extern lv_obj_t * ui_navigate_panel_headernav;
extern lv_obj_t * ui_navigate_label_headerlabel;
void ui_event_navigate_button_btnclose(lv_event_t * e);
extern lv_obj_t * ui_navigate_button_btnclose;
extern lv_obj_t * ui_navigate_label_btncloselabel;
extern lv_obj_t * ui_navigate_container_body;
extern lv_obj_t * ui_navigate_container_menuitem0;
extern lv_obj_t * ui_navigate_label_menuitemlabel;
extern lv_obj_t * ui_navigate_label_menuitemvalue;
extern lv_obj_t * ui_navigate_container_menuitem1;
extern lv_obj_t * ui_navigate_label_menuitemlabel1;
extern lv_obj_t * ui_navigate_label_menuitemvalue1;
extern lv_obj_t * ui_navigate_container_menuitem2;
extern lv_obj_t * ui_navigate_label_menuitemlabel2;
extern lv_obj_t * ui_navigate_label_menuitemvalue2;
extern lv_obj_t * ui_navigate_container_menuitem3;
extern lv_obj_t * ui_navigate_label_menuitemlabel3;
extern lv_obj_t * ui_navigate_label_menuitemvalue3;
extern lv_obj_t * ui_navigate_container_menuitem4;
extern lv_obj_t * ui_navigate_label_menuitemlabel4;
extern lv_obj_t * ui_navigate_label_menuitemvalue4;
extern lv_obj_t * ui_navigate_container_menuitem5;
extern lv_obj_t * ui_navigate_label_menuitemlabel5;
extern lv_obj_t * ui_navigate_label_menuitemvalue5;
extern lv_obj_t * ui_navigate_container_menuitem6;
extern lv_obj_t * ui_navigate_label_menuitemlabel6;
extern lv_obj_t * ui_navigate_label_menuitemvalue6;
extern lv_obj_t * ui_navigate_container_menuitem7;
extern lv_obj_t * ui_navigate_label_menuitemlabel7;
extern lv_obj_t * ui_navigate_label_menuitemvalue7;
extern lv_obj_t * ui_navigate_container_menuitem8;
extern lv_obj_t * ui_navigate_label_menuitemlabel8;
extern lv_obj_t * ui_navigate_label_menuitemvalue8;
extern lv_obj_t * ui_navigate_container_footer;
extern lv_obj_t * ui_navigate_panel_footernav;
void ui_event_navigate_button_btnprev(lv_event_t * e);
extern lv_obj_t * ui_navigate_button_btnprev;
extern lv_obj_t * ui_navigate_label_btnprevlabel;
void ui_event_navigate_button_btnnext(lv_event_t * e);
extern lv_obj_t * ui_navigate_button_btnnext;
extern lv_obj_t * ui_navigate_label_btnnextlabel;
void ui_event_navigate_button_btnenter(lv_event_t * e);
extern lv_obj_t * ui_navigate_button_btnenter;
extern lv_obj_t * ui_navigate_label_btnenterlabel;
// SCREEN: ui_edit
void ui_edit_screen_init(void);
extern lv_obj_t * ui_edit;
extern lv_obj_t * ui_edit_panel_headeredit;
extern lv_obj_t * ui_edit_label_headerlabel2;
void ui_event_edit_button_btnclose2(lv_event_t * e);
extern lv_obj_t * ui_edit_button_btnclose2;
extern lv_obj_t * ui_edit_label_btncloselabel2;
extern lv_obj_t * ui_edit_container_bodyedit;
extern lv_obj_t * ui_edit_textarea_vareditinput;
extern lv_obj_t * ui_edit_container_footeredit;
extern lv_obj_t * ui_edit_keyboard_keyboardedit;
// SCREEN: ui_jog
void ui_jog_screen_init(void);
extern lv_obj_t * ui_jog;
extern lv_obj_t * ui_jog_panel_headernav1;
extern lv_obj_t * ui_jog_label_headerlabel1;
void ui_event_jog_button_btnclose1(lv_event_t * e);
extern lv_obj_t * ui_jog_button_btnclose1;
extern lv_obj_t * ui_jog_label_btncloselabel1;
extern lv_obj_t * ui_jog_container_body1;
extern lv_obj_t * ui_jog_panel_panel1;
extern lv_obj_t * ui_jog_container_container2;
extern lv_obj_t * ui_jog_label_label4;
extern lv_obj_t * ui_jog_roller_jogdist;
extern lv_obj_t * ui_jog_container_container4;
extern lv_obj_t * ui_jog_label_label5;
extern lv_obj_t * ui_jog_roller_jogfeed;
extern lv_obj_t * ui_jog_container_container5;
extern lv_obj_t * ui_jog_label_label6;
extern lv_obj_t * ui_jog_roller_jogaxis;
extern lv_obj_t * ui_jog_container_container6;
extern lv_obj_t * ui_jog_button_btnjogplus;
extern lv_obj_t * ui_jog_label_label2;
extern lv_obj_t * ui_jog_button_btnjogcancel;
extern lv_obj_t * ui_jog_label_label3;
extern lv_obj_t * ui_jog_button_btnjogminus;
extern lv_obj_t * ui_jog_label_label7;
extern lv_obj_t * ui_startevents____initial_actions0;


LV_IMG_DECLARE(ui_img_ucnc_logo_png);    // assets/uCNC_logo.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
