// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: uCNC-GFX

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "src/modules/system_menu.h"

void touch_btn_hold_cb(lv_event_t * e);
void btn_idle_cb(lv_event_t * e);
void touch_btn_home_cb(lv_event_t * e);
void touch_btn_jog_cb(lv_event_t * e);
void touch_btn_settings_cb(lv_event_t * e);
void touch_btn_prev_cb(lv_event_t * e);
void touch_btn_next_cb(lv_event_t * e);
void touch_btn_enter_cb(lv_event_t * e);
void touch_btn_close_cb(lv_event_t * e);
void touch_kb_ready_ev(lv_event_t * e);
void touch_btn_jogplus_cb(lv_event_t * e);
void touch_btn_jogcancel_cb(lv_event_t * e);
void touch_btn_jogminus_cb(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
