// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: uCNC-GFX

#include "ui.h"

void ui_edit_screen_init(void)
{
    ui_edit = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_edit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_edit, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_edit, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_edit_panel_headeredit = lv_obj_create(ui_edit);
    lv_obj_set_width(ui_edit_panel_headeredit, lv_pct(100));
    lv_obj_set_height(ui_edit_panel_headeredit, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_edit_panel_headeredit, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_edit_panel_headeredit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_edit_panel_headeredit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_edit_panel_headeredit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_edit_panel_headeredit, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_edit_panel_headeredit, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_edit_label_headerlabel2 = lv_label_create(ui_edit_panel_headeredit);
    lv_obj_set_width(ui_edit_label_headerlabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_edit_label_headerlabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_edit_label_headerlabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_edit_label_headerlabel2, "text");

    ui_edit_button_btnclose2 = lv_button_create(ui_edit_panel_headeredit);
    lv_obj_set_width(ui_edit_button_btnclose2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_edit_button_btnclose2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_edit_button_btnclose2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_edit_button_btnclose2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_edit_button_btnclose2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_edit_button_btnclose2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_edit_button_btnclose2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_edit_label_btncloselabel2 = lv_label_create(ui_edit_button_btnclose2);
    lv_obj_set_width(ui_edit_label_btncloselabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_edit_label_btncloselabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_edit_label_btncloselabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_edit_label_btncloselabel2, "X");

    ui_edit_container_bodyedit = lv_obj_create(ui_edit);
    lv_obj_remove_style_all(ui_edit_container_bodyedit);
    lv_obj_set_width(ui_edit_container_bodyedit, lv_pct(100));
    lv_obj_set_height(ui_edit_container_bodyedit, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_edit_container_bodyedit, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_edit_container_bodyedit, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_edit_textarea_vareditinput = lv_textarea_create(ui_edit_container_bodyedit);
    lv_obj_set_height(ui_edit_textarea_vareditinput, 70);
    lv_obj_set_width(ui_edit_textarea_vareditinput, lv_pct(75));
    lv_obj_set_align(ui_edit_textarea_vareditinput, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_edit_textarea_vareditinput, "value");
    lv_textarea_set_placeholder_text(ui_edit_textarea_vareditinput, "Placeholder...");



    ui_edit_container_footeredit = lv_obj_create(ui_edit);
    lv_obj_remove_style_all(ui_edit_container_footeredit);
    lv_obj_set_width(ui_edit_container_footeredit, lv_pct(100));
    lv_obj_set_height(ui_edit_container_footeredit, lv_pct(50));
    lv_obj_set_align(ui_edit_container_footeredit, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_edit_container_footeredit, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_edit_keyboard_keyboardedit = lv_keyboard_create(ui_edit_container_footeredit);
    lv_keyboard_set_mode(ui_edit_keyboard_keyboardedit, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_edit_keyboard_keyboardedit, lv_pct(100));
    lv_obj_set_height(ui_edit_keyboard_keyboardedit, lv_pct(100));
    lv_obj_set_align(ui_edit_keyboard_keyboardedit, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_edit_button_btnclose2, ui_event_edit_button_btnclose2, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_edit_keyboard_keyboardedit, ui_edit_textarea_vareditinput);

}
