// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: uCNC-GFX

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void touch_btn_prev_cb(lv_event_t * e);
void touch_btn_next_cb(lv_event_t * e);
void touch_btn_enter_cb(lv_event_t * e);
void touch_btn_close_cb(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
