// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: uCNC-GFX

#include "ui.h"

void touch_btn_home_cb(lv_event_t * e)
{
	// Your code here
}

void touch_btn_hold_cb(lv_event_t * e)
{
	// Your code here
}

void btn_idle_cb(lv_event_t * e)
{
	// Your code here
}

void touch_btn_prev_cb(lv_event_t * e)
{
	// Your code here
}

void touch_btn_next_cb(lv_event_t * e)
{
	// Your code here
}

void touch_btn_enter_cb(lv_event_t * e)
{
	// Your code here
}

void touch_btn_close_cb(lv_event_t * e)
{
	// Your code here
}

void touch_btn_jogplus_cb(lv_event_t * e)
{
	// Your code here
}

void touch_btn_jogcancel_cb(lv_event_t * e)
{
	// Your code here
}

void touch_btn_jogminus_cb(lv_event_t * e)
{
	// Your code here
}
