// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: uCNC-GFX

#include "ui.h"

void ui_jog_screen_init(void)
{
    ui_jog = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_jog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_jog, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_jog, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_left(ui_jog, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_jog, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_jog, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_jog, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_jog_panel_headernav1 = lv_obj_create(ui_jog);
    lv_obj_set_width(ui_jog_panel_headernav1, lv_pct(100));
    lv_obj_set_height(ui_jog_panel_headernav1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_jog_panel_headernav1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_jog_panel_headernav1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_jog_panel_headernav1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_jog_panel_headernav1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_jog_panel_headernav1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_jog_panel_headernav1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_jog_label_headerlabel1 = lv_label_create(ui_jog_panel_headernav1);
    lv_obj_set_width(ui_jog_label_headerlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_jog_label_headerlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_jog_label_headerlabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_jog_label_headerlabel1, "JOG");

    ui_jog_button_btnclose1 = lv_button_create(ui_jog_panel_headernav1);
    lv_obj_set_width(ui_jog_button_btnclose1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_jog_button_btnclose1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_jog_button_btnclose1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_jog_button_btnclose1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_jog_button_btnclose1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_jog_button_btnclose1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_jog_button_btnclose1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_jog_label_btncloselabel1 = lv_label_create(ui_jog_button_btnclose1);
    lv_obj_set_width(ui_jog_label_btncloselabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_jog_label_btncloselabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_jog_label_btncloselabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_jog_label_btncloselabel1, "X");

    ui_jog_container_body1 = lv_obj_create(ui_jog);
    lv_obj_remove_style_all(ui_jog_container_body1);
    lv_obj_set_width(ui_jog_container_body1, lv_pct(100));
    lv_obj_set_flex_grow(ui_jog_container_body1, 1);
    lv_obj_set_align(ui_jog_container_body1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_jog_container_body1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_jog_container_body1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_jog_container_body1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_jog_container_body1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_jog_container_body1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_jog_container_body1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_jog_container_body1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_jog_container_body1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_jog_container_body1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_jog_panel_panel1 = lv_obj_create(ui_jog_container_body1);
    lv_obj_set_height(ui_jog_panel_panel1, lv_pct(100));
    lv_obj_set_flex_grow(ui_jog_panel_panel1, 1);
    lv_obj_set_align(ui_jog_panel_panel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_jog_panel_panel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_jog_panel_panel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_jog_panel_panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_jog_container_container2 = lv_obj_create(ui_jog_panel_panel1);
    lv_obj_remove_style_all(ui_jog_container_container2);
    lv_obj_set_height(ui_jog_container_container2, lv_pct(100));
    lv_obj_set_flex_grow(ui_jog_container_container2, 1);
    lv_obj_set_align(ui_jog_container_container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_jog_container_container2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_jog_container_container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_jog_container_container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_jog_container_container2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_jog_container_container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_jog_label_label4 = lv_label_create(ui_jog_container_container2);
    lv_obj_set_width(ui_jog_label_label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_jog_label_label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_jog_label_label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_jog_label_label4, "Dist.");

    ui_jog_roller_jogdist = lv_roller_create(ui_jog_container_container2);
    lv_roller_set_options(ui_jog_roller_jogdist, "0.001\n0.01\n0.1\n1\n10\n100", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_jog_roller_jogdist, lv_pct(100));
    lv_obj_set_flex_grow(ui_jog_roller_jogdist, 1);
    lv_obj_set_align(ui_jog_roller_jogdist, LV_ALIGN_CENTER);

    ui_jog_container_container4 = lv_obj_create(ui_jog_panel_panel1);
    lv_obj_remove_style_all(ui_jog_container_container4);
    lv_obj_set_height(ui_jog_container_container4, lv_pct(100));
    lv_obj_set_flex_grow(ui_jog_container_container4, 1);
    lv_obj_set_align(ui_jog_container_container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_jog_container_container4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_jog_container_container4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_jog_container_container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_jog_container_container4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_jog_container_container4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_jog_label_label5 = lv_label_create(ui_jog_container_container4);
    lv_obj_set_width(ui_jog_label_label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_jog_label_label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_jog_label_label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_jog_label_label5, "Feed");

    ui_jog_roller_jogfeed = lv_roller_create(ui_jog_container_container4);
    lv_roller_set_options(ui_jog_roller_jogfeed, "1\n10\n50\n100\n250\n500\n750\n1000", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_jog_roller_jogfeed, lv_pct(100));
    lv_obj_set_flex_grow(ui_jog_roller_jogfeed, 1);
    lv_obj_set_align(ui_jog_roller_jogfeed, LV_ALIGN_CENTER);

    ui_jog_container_container5 = lv_obj_create(ui_jog_panel_panel1);
    lv_obj_remove_style_all(ui_jog_container_container5);
    lv_obj_set_height(ui_jog_container_container5, lv_pct(100));
    lv_obj_set_flex_grow(ui_jog_container_container5, 1);
    lv_obj_set_align(ui_jog_container_container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_jog_container_container5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_jog_container_container5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_jog_container_container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_jog_container_container5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_jog_container_container5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_jog_label_label6 = lv_label_create(ui_jog_container_container5);
    lv_obj_set_width(ui_jog_label_label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_jog_label_label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_jog_label_label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_jog_label_label6, "Axis");

    ui_jog_roller_jogaxis = lv_roller_create(ui_jog_container_container5);
    lv_roller_set_options(ui_jog_roller_jogaxis, "X\nY\nZ\nA\nB\nC", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_jog_roller_jogaxis, lv_pct(100));
    lv_obj_set_flex_grow(ui_jog_roller_jogaxis, 1);
    lv_obj_set_align(ui_jog_roller_jogaxis, LV_ALIGN_CENTER);

    ui_jog_container_container6 = lv_obj_create(ui_jog_panel_panel1);
    lv_obj_remove_style_all(ui_jog_container_container6);
    lv_obj_set_height(ui_jog_container_container6, lv_pct(100));
    lv_obj_set_flex_grow(ui_jog_container_container6, 1);
    lv_obj_set_align(ui_jog_container_container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_jog_container_container6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_jog_container_container6, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_jog_container_container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_jog_button_btnjogplus = lv_button_create(ui_jog_container_container6);
    lv_obj_set_width(ui_jog_button_btnjogplus, 100);
    lv_obj_set_height(ui_jog_button_btnjogplus, 50);
    lv_obj_set_align(ui_jog_button_btnjogplus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_jog_button_btnjogplus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_jog_button_btnjogplus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_jog_button_btnjogplus, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_jog_label_label2 = lv_label_create(ui_jog_button_btnjogplus);
    lv_obj_set_width(ui_jog_label_label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_jog_label_label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_jog_label_label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_jog_label_label2, "+");

    ui_jog_button_btnjogcancel = lv_button_create(ui_jog_container_container6);
    lv_obj_set_width(ui_jog_button_btnjogcancel, 100);
    lv_obj_set_height(ui_jog_button_btnjogcancel, 50);
    lv_obj_set_align(ui_jog_button_btnjogcancel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_jog_button_btnjogcancel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_jog_button_btnjogcancel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_jog_button_btnjogcancel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_jog_button_btnjogcancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_jog_label_label3 = lv_label_create(ui_jog_button_btnjogcancel);
    lv_obj_set_width(ui_jog_label_label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_jog_label_label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_jog_label_label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_jog_label_label3, "Cancel");

    ui_jog_button_btnjogminus = lv_button_create(ui_jog_container_container6);
    lv_obj_set_width(ui_jog_button_btnjogminus, 100);
    lv_obj_set_height(ui_jog_button_btnjogminus, 50);
    lv_obj_set_align(ui_jog_button_btnjogminus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_jog_button_btnjogminus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_jog_button_btnjogminus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_jog_button_btnjogminus, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_jog_label_label7 = lv_label_create(ui_jog_button_btnjogminus);
    lv_obj_set_width(ui_jog_label_label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_jog_label_label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_jog_label_label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_jog_label_label7, "-");

    lv_obj_add_event_cb(ui_jog_button_btnclose1, ui_event_jog_button_btnclose1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_jog_button_btnjogplus, ui_event_jog_button_btnjogplus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_jog_button_btnjogcancel, ui_event_jog_button_btnjogcancel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_jog_button_btnjogminus, ui_event_jog_button_btnjogminus, LV_EVENT_ALL, NULL);

}
