// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: uCNC-GFX

#include "ui.h"

void ui_navigate_screen_init(void)
{
    ui_navigate = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_navigate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_navigate, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_navigate, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_left(ui_navigate, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_navigate, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_navigate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_navigate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_navigate_panel_headernav = lv_obj_create(ui_navigate);
    lv_obj_set_width(ui_navigate_panel_headernav, lv_pct(100));
    lv_obj_set_height(ui_navigate_panel_headernav, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_navigate_panel_headernav, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_navigate_panel_headernav, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_navigate_panel_headernav, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_navigate_panel_headernav, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_navigate_panel_headernav, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_navigate_panel_headernav, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_navigate_label_headerlabel = lv_label_create(ui_navigate_panel_headernav);
    lv_obj_set_width(ui_navigate_label_headerlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_navigate_label_headerlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_navigate_label_headerlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_navigate_label_headerlabel, "text");

    ui_navigate_button_btnclose = lv_button_create(ui_navigate_panel_headernav);
    lv_obj_set_width(ui_navigate_button_btnclose, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_navigate_button_btnclose, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_navigate_button_btnclose, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_navigate_button_btnclose, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_navigate_button_btnclose, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_navigate_button_btnclose, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_navigate_button_btnclose, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_navigate_label_btncloselabel = lv_label_create(ui_navigate_button_btnclose);
    lv_obj_set_width(ui_navigate_label_btncloselabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_navigate_label_btncloselabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_navigate_label_btncloselabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_navigate_label_btncloselabel, "X");

    ui_navigate_container_body = lv_obj_create(ui_navigate);
    lv_obj_remove_style_all(ui_navigate_container_body);
    lv_obj_set_width(ui_navigate_container_body, lv_pct(100));
    lv_obj_set_flex_grow(ui_navigate_container_body, 1);
    lv_obj_set_align(ui_navigate_container_body, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_navigate_container_body, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_navigate_container_body, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_navigate_container_body, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_navigate_container_body, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_navigate_container_body, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_navigate_container_body, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_navigate_container_body, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_navigate_container_body, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_navigate_container_body, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_navigate_container_menuitem0 = lv_obj_create(ui_navigate_container_body);
    lv_obj_remove_style_all(ui_navigate_container_menuitem0);
    lv_obj_set_width(ui_navigate_container_menuitem0, lv_pct(100));
    lv_obj_set_height(ui_navigate_container_menuitem0, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_navigate_container_menuitem0, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_navigate_container_menuitem0, LV_STATE_FOCUSED);       /// States
    lv_obj_remove_flag(ui_navigate_container_menuitem0, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_navigate_container_menuitem0, lv_color_hex(0x274E88), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_opa(ui_navigate_container_menuitem0, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_color(ui_navigate_container_menuitem0, lv_color_hex(0x444444), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_navigate_container_menuitem0, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_navigate_label_menuitemlabel = lv_label_create(ui_navigate_container_menuitem0);
    lv_obj_set_width(ui_navigate_label_menuitemlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_navigate_label_menuitemlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_navigate_label_menuitemlabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_navigate_label_menuitemlabel, "text");

    ui_navigate_label_menuitemvalue = lv_label_create(ui_navigate_container_menuitem0);
    lv_obj_set_width(ui_navigate_label_menuitemvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_navigate_label_menuitemvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_navigate_label_menuitemvalue, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_navigate_label_menuitemvalue, "text");

    ui_navigate_container_menuitem1 = lv_obj_create(ui_navigate_container_body);
    lv_obj_remove_style_all(ui_navigate_container_menuitem1);
    lv_obj_set_width(ui_navigate_container_menuitem1, lv_pct(100));
    lv_obj_set_height(ui_navigate_container_menuitem1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_navigate_container_menuitem1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_navigate_container_menuitem1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_navigate_label_menuitemlabel1 = lv_label_create(ui_navigate_container_menuitem1);
    lv_obj_set_width(ui_navigate_label_menuitemlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_navigate_label_menuitemlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_navigate_label_menuitemlabel1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_navigate_label_menuitemlabel1, "text");

    ui_navigate_label_menuitemvalue1 = lv_label_create(ui_navigate_container_menuitem1);
    lv_obj_set_width(ui_navigate_label_menuitemvalue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_navigate_label_menuitemvalue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_navigate_label_menuitemvalue1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_navigate_label_menuitemvalue1, "text");

    ui_navigate_container_menuitem2 = lv_obj_create(ui_navigate_container_body);
    lv_obj_remove_style_all(ui_navigate_container_menuitem2);
    lv_obj_set_width(ui_navigate_container_menuitem2, lv_pct(100));
    lv_obj_set_height(ui_navigate_container_menuitem2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_navigate_container_menuitem2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_navigate_container_menuitem2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_navigate_label_menuitemlabel2 = lv_label_create(ui_navigate_container_menuitem2);
    lv_obj_set_width(ui_navigate_label_menuitemlabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_navigate_label_menuitemlabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_navigate_label_menuitemlabel2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_navigate_label_menuitemlabel2, "text");

    ui_navigate_label_menuitemvalue2 = lv_label_create(ui_navigate_container_menuitem2);
    lv_obj_set_width(ui_navigate_label_menuitemvalue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_navigate_label_menuitemvalue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_navigate_label_menuitemvalue2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_navigate_label_menuitemvalue2, "text");

    ui_navigate_container_menuitem3 = lv_obj_create(ui_navigate_container_body);
    lv_obj_remove_style_all(ui_navigate_container_menuitem3);
    lv_obj_set_width(ui_navigate_container_menuitem3, lv_pct(100));
    lv_obj_set_height(ui_navigate_container_menuitem3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_navigate_container_menuitem3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_navigate_container_menuitem3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_navigate_label_menuitemlabel3 = lv_label_create(ui_navigate_container_menuitem3);
    lv_obj_set_width(ui_navigate_label_menuitemlabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_navigate_label_menuitemlabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_navigate_label_menuitemlabel3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_navigate_label_menuitemlabel3, "text");

    ui_navigate_label_menuitemvalue3 = lv_label_create(ui_navigate_container_menuitem3);
    lv_obj_set_width(ui_navigate_label_menuitemvalue3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_navigate_label_menuitemvalue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_navigate_label_menuitemvalue3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_navigate_label_menuitemvalue3, "text");

    ui_navigate_container_menuitem4 = lv_obj_create(ui_navigate_container_body);
    lv_obj_remove_style_all(ui_navigate_container_menuitem4);
    lv_obj_set_width(ui_navigate_container_menuitem4, lv_pct(100));
    lv_obj_set_height(ui_navigate_container_menuitem4, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_navigate_container_menuitem4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_navigate_container_menuitem4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_navigate_label_menuitemlabel4 = lv_label_create(ui_navigate_container_menuitem4);
    lv_obj_set_width(ui_navigate_label_menuitemlabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_navigate_label_menuitemlabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_navigate_label_menuitemlabel4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_navigate_label_menuitemlabel4, "text");

    ui_navigate_label_menuitemvalue4 = lv_label_create(ui_navigate_container_menuitem4);
    lv_obj_set_width(ui_navigate_label_menuitemvalue4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_navigate_label_menuitemvalue4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_navigate_label_menuitemvalue4, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_navigate_label_menuitemvalue4, "text");

    ui_navigate_container_menuitem5 = lv_obj_create(ui_navigate_container_body);
    lv_obj_remove_style_all(ui_navigate_container_menuitem5);
    lv_obj_set_width(ui_navigate_container_menuitem5, lv_pct(100));
    lv_obj_set_height(ui_navigate_container_menuitem5, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_navigate_container_menuitem5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_navigate_container_menuitem5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_navigate_label_menuitemlabel5 = lv_label_create(ui_navigate_container_menuitem5);
    lv_obj_set_width(ui_navigate_label_menuitemlabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_navigate_label_menuitemlabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_navigate_label_menuitemlabel5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_navigate_label_menuitemlabel5, "text");

    ui_navigate_label_menuitemvalue5 = lv_label_create(ui_navigate_container_menuitem5);
    lv_obj_set_width(ui_navigate_label_menuitemvalue5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_navigate_label_menuitemvalue5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_navigate_label_menuitemvalue5, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_navigate_label_menuitemvalue5, "text");

    ui_navigate_container_menuitem6 = lv_obj_create(ui_navigate_container_body);
    lv_obj_remove_style_all(ui_navigate_container_menuitem6);
    lv_obj_set_width(ui_navigate_container_menuitem6, lv_pct(100));
    lv_obj_set_height(ui_navigate_container_menuitem6, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_navigate_container_menuitem6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_navigate_container_menuitem6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_navigate_label_menuitemlabel6 = lv_label_create(ui_navigate_container_menuitem6);
    lv_obj_set_width(ui_navigate_label_menuitemlabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_navigate_label_menuitemlabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_navigate_label_menuitemlabel6, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_navigate_label_menuitemlabel6, "text");

    ui_navigate_label_menuitemvalue6 = lv_label_create(ui_navigate_container_menuitem6);
    lv_obj_set_width(ui_navigate_label_menuitemvalue6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_navigate_label_menuitemvalue6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_navigate_label_menuitemvalue6, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_navigate_label_menuitemvalue6, "text");

    ui_navigate_container_menuitem7 = lv_obj_create(ui_navigate_container_body);
    lv_obj_remove_style_all(ui_navigate_container_menuitem7);
    lv_obj_set_width(ui_navigate_container_menuitem7, lv_pct(100));
    lv_obj_set_height(ui_navigate_container_menuitem7, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_navigate_container_menuitem7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_navigate_container_menuitem7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_navigate_label_menuitemlabel7 = lv_label_create(ui_navigate_container_menuitem7);
    lv_obj_set_width(ui_navigate_label_menuitemlabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_navigate_label_menuitemlabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_navigate_label_menuitemlabel7, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_navigate_label_menuitemlabel7, "text");

    ui_navigate_label_menuitemvalue7 = lv_label_create(ui_navigate_container_menuitem7);
    lv_obj_set_width(ui_navigate_label_menuitemvalue7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_navigate_label_menuitemvalue7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_navigate_label_menuitemvalue7, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_navigate_label_menuitemvalue7, "text");

    ui_navigate_container_menuitem8 = lv_obj_create(ui_navigate_container_body);
    lv_obj_remove_style_all(ui_navigate_container_menuitem8);
    lv_obj_set_width(ui_navigate_container_menuitem8, lv_pct(100));
    lv_obj_set_height(ui_navigate_container_menuitem8, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_navigate_container_menuitem8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_navigate_container_menuitem8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_navigate_label_menuitemlabel8 = lv_label_create(ui_navigate_container_menuitem8);
    lv_obj_set_width(ui_navigate_label_menuitemlabel8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_navigate_label_menuitemlabel8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_navigate_label_menuitemlabel8, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_navigate_label_menuitemlabel8, "text");

    ui_navigate_label_menuitemvalue8 = lv_label_create(ui_navigate_container_menuitem8);
    lv_obj_set_width(ui_navigate_label_menuitemvalue8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_navigate_label_menuitemvalue8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_navigate_label_menuitemvalue8, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_navigate_label_menuitemvalue8, "text");

    ui_navigate_container_footer = lv_obj_create(ui_navigate);
    lv_obj_remove_style_all(ui_navigate_container_footer);
    lv_obj_set_width(ui_navigate_container_footer, lv_pct(100));
    lv_obj_set_height(ui_navigate_container_footer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_navigate_container_footer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_navigate_container_footer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_navigate_container_footer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_navigate_container_footer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_navigate_container_footer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_navigate_container_footer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_navigate_container_footer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_navigate_container_footer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_navigate_container_footer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_navigate_container_footer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_navigate_panel_footernav = lv_obj_create(ui_navigate);
    lv_obj_set_width(ui_navigate_panel_footernav, lv_pct(100));
    lv_obj_set_height(ui_navigate_panel_footernav, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_navigate_panel_footernav, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_navigate_panel_footernav, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_navigate_panel_footernav, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_navigate_panel_footernav, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_navigate_panel_footernav, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_navigate_panel_footernav, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_navigate_panel_footernav, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_navigate_panel_footernav, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_navigate_panel_footernav, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_navigate_panel_footernav, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_navigate_button_btnprev = lv_button_create(ui_navigate_panel_footernav);
    lv_obj_set_height(ui_navigate_button_btnprev, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_grow(ui_navigate_button_btnprev, 1);
    lv_obj_set_align(ui_navigate_button_btnprev, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_navigate_button_btnprev, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_navigate_button_btnprev, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_navigate_label_btnprevlabel = lv_label_create(ui_navigate_button_btnprev);
    lv_obj_set_width(ui_navigate_label_btnprevlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_navigate_label_btnprevlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_navigate_label_btnprevlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_navigate_label_btnprevlabel, "Back/Down");

    ui_navigate_button_btnnext = lv_button_create(ui_navigate_panel_footernav);
    lv_obj_set_height(ui_navigate_button_btnnext, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_grow(ui_navigate_button_btnnext, 1);
    lv_obj_set_align(ui_navigate_button_btnnext, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_navigate_button_btnnext, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_navigate_button_btnnext, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_navigate_label_btnnextlabel = lv_label_create(ui_navigate_button_btnnext);
    lv_obj_set_width(ui_navigate_label_btnnextlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_navigate_label_btnnextlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_navigate_label_btnnextlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_navigate_label_btnnextlabel, "Next/Up");

    ui_navigate_button_btnenter = lv_button_create(ui_navigate_panel_footernav);
    lv_obj_set_height(ui_navigate_button_btnenter, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_grow(ui_navigate_button_btnenter, 1);
    lv_obj_set_align(ui_navigate_button_btnenter, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_navigate_button_btnenter, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_navigate_button_btnenter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_navigate_label_btnenterlabel = lv_label_create(ui_navigate_button_btnenter);
    lv_obj_set_width(ui_navigate_label_btnenterlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_navigate_label_btnenterlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_navigate_label_btnenterlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_navigate_label_btnenterlabel, "Enter/Set");

    lv_obj_add_event_cb(ui_navigate_button_btnclose, ui_event_navigate_button_btnclose, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_navigate_button_btnprev, ui_event_navigate_button_btnprev, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_navigate_button_btnnext, ui_event_navigate_button_btnnext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_navigate_button_btnenter, ui_event_navigate_button_btnenter, LV_EVENT_ALL, NULL);

}
